---
abstract: 'Syntactic sugar for running a method while in a directory'
author:
  - 'Rob Hoelz <rob@hoelz.ro>'
build_requires:
  Cwd: 0
  File::Spec: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::Builder: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Role-WithWorkingDirectory
requires:
  Moose: 2
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=MooseX-Role-WithWorkingDirectory
version: 0.01
